services:
  - type: web
    name: staccato-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YT_DLP_PATH
        value: yt-dlp
